// Command genoui compiles IEEE MA-L, MA-M, and MA-S CSV registries into
// sorted, allocation-free lookup tables used by omnidiscover.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/csv"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

type entry struct {
	prefix uint64
	name   string
}

func main() {
	mal := flag.String("mal", "", "IEEE MA-L CSV path")
	mam := flag.String("mam", "", "IEEE MA-M CSV path")
	mas := flag.String("mas", "", "IEEE MA-S CSV path")
	out := flag.String("out", "pkg/omnidiscover/vendor_registry_gen.go", "generated Go output")
	flag.Parse()
	if *mal == "" || *mam == "" || *mas == "" {
		fatalf("-mal, -mam, and -mas are required")
	}

	groups := make([][]entry, 3)
	var err error
	for i, source := range []struct {
		path string
		bits int
	}{{*mal, 24}, {*mam, 28}, {*mas, 36}} {
		groups[i], err = readRegistry(source.path, source.bits)
		if err != nil {
			fatalf("read %s: %v", source.path, err)
		}
	}

	var names bytes.Buffer
	nameRefs := make(map[string]uint32, 8192)
	refs := make([][]uint32, len(groups))
	for group := range groups {
		refs[group] = make([]uint32, len(groups[group]))
		for i := range groups[group] {
			name := groups[group][i].name
			if ref, ok := nameRefs[name]; ok {
				refs[group][i] = ref
				continue
			}
			if len(name) > 255 {
				fatalf("organization name exceeds 255 bytes: %q", name)
			}
			if names.Len() >= 1<<24 {
				fatalf("organization name arena exceeds 24-bit offset")
			}
			ref := uint32(names.Len()<<8 | len(name))
			nameRefs[name] = ref
			refs[group][i] = ref
			names.WriteString(name)
		}
	}

	var generated bytes.Buffer
	fmt.Fprintln(&generated, "// Code generated by utils/genoui from the IEEE public MA-L, MA-M, and MA-S registries; DO NOT EDIT.")
	for _, source := range []struct {
		name string
		path string
	}{{"MA-L", *mal}, {"MA-M", *mam}, {"MA-S", *mas}} {
		digest, err := fileSHA256(source.path)
		if err != nil {
			fatalf("hash %s: %v", source.path, err)
		}
		fmt.Fprintf(&generated, "// %s SHA-256: %x\n", source.name, digest)
	}
	fmt.Fprintln(&generated, "package omnidiscover")
	fmt.Fprintf(&generated, "\nconst vendorNameData = %s\n", strconv.Quote(names.String()))
	bits := []int{24, 28, 36}
	for group := range groups {
		writePrefixes(&generated, bits[group], groups[group])
		writeUint32s(&generated, fmt.Sprintf("vendor%dNameRefs", bits[group]), refs[group])
		writeBuckets(&generated, bits[group], groups[group])
	}
	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fatalf("write %s: %v", *out, err)
	}
}

func fileSHA256(path string) ([32]byte, error) {
	f, err := os.Open(path)
	if err != nil {
		return [32]byte{}, err
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return [32]byte{}, err
	}
	var digest [32]byte
	copy(digest[:], h.Sum(nil))
	return digest, nil
}

func readRegistry(path string, bits int) ([]entry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	r := csv.NewReader(f)
	r.FieldsPerRecord = -1
	if _, err := r.Read(); err != nil {
		return nil, err
	}
	byPrefix := make(map[uint64]string, 4096)
	for {
		record, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		if len(record) < 3 {
			continue
		}
		assignment := strings.TrimSpace(record[1])
		name := strings.TrimSpace(record[2])
		if assignment == "" || name == "" {
			continue
		}
		prefix, err := strconv.ParseUint(assignment, 16, bits)
		if err != nil {
			return nil, fmt.Errorf("assignment %q: %w", assignment, err)
		}
		// A few historical MA-L assignments have more than one public row.
		// The registry's last row is its current display name.
		byPrefix[prefix] = name
	}
	entries := make([]entry, 0, len(byPrefix))
	for prefix, name := range byPrefix {
		entries = append(entries, entry{prefix: prefix, name: name})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].prefix < entries[j].prefix })
	return entries, nil
}

func writePrefixes(w io.Writer, bits int, entries []entry) {
	typ := "uint32"
	if bits > 28 {
		typ = "uint64"
	}
	fmt.Fprintf(w, "\nvar vendor%dPrefixes = [...]%s{\n", bits, typ)
	for i, e := range entries {
		if i%8 == 0 {
			fmt.Fprint(w, "\t")
		}
		fmt.Fprintf(w, "0x%x,", e.prefix)
		if i%8 == 7 || i == len(entries)-1 {
			fmt.Fprintln(w)
		}
	}
	fmt.Fprintln(w, "}")
}

func writeUint32s(w io.Writer, name string, values []uint32) {
	fmt.Fprintf(w, "\nvar %s = [...]uint32{\n", name)
	for i, value := range values {
		if i%8 == 0 {
			fmt.Fprint(w, "\t")
		}
		fmt.Fprintf(w, "0x%x,", value)
		if i%8 == 7 || i == len(values)-1 {
			fmt.Fprintln(w)
		}
	}
	fmt.Fprintln(w, "}")
}

func writeBuckets(w io.Writer, bits int, entries []entry) {
	// A 12-bit first-level index reduces MA-L lookup from roughly sixteen
	// comparisons to a binary search across about ten candidates.
	var buckets [4097]uint16
	entry := 0
	for bucket := 0; bucket < 4096; bucket++ {
		buckets[bucket] = uint16(entry)
		for entry < len(entries) && int(entries[entry].prefix>>uint(bits-12)) == bucket {
			entry++
		}
	}
	buckets[4096] = uint16(len(entries))
	fmt.Fprintf(w, "\nvar vendor%dBuckets = [...]uint16{\n", bits)
	for i, value := range buckets {
		if i%16 == 0 {
			fmt.Fprint(w, "\t")
		}
		fmt.Fprintf(w, "%d,", value)
		if i%16 == 15 || i == len(buckets)-1 {
			fmt.Fprintln(w)
		}
	}
	fmt.Fprintln(w, "}")
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "genoui: "+format+"\n", args...)
	os.Exit(1)
}
